/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of
 *
 * @see [./test/files/url-source.spec.js]{@link ./test/files/url-source.spec.js}
 *
 **/
import { expect } from 'aegir/chai'
import all from 'it-all'
import urlSource from '../../src/files/url-source.js'
import { Buffer } from 'buffer'
/* eslint-env mocha */

describe('url-source', function () {
  it('can get url content', async function () {
    const content = 'foo'
    const file = urlSource(`${process.env.ECHO_SERVER}/download?data=${content}`)

    expect(file).to.have.property('path', 'download')

    if (file && file.content) {
      await expect(all(file.content)).to.eventually.deep.equal([Buffer.from(content)])
    } else {
      throw new Error('empty response')
    }
  })
})
